bag = rosbag('12_flying.bag')

model_names = [ "dragonfly1", ...
                "dragonfly2", ...
                "dragonfly3", ...
                "dragonfly4", ...
                "dragonfly5", ...
                "dragonfly6", ...
                "dragonfly7", ...
                "dragonfly8", ...
                "dragonfly10", ...
                "dragonfly11", ...
                "dragonfly13", ...
                "dragonfly14"];
            
starting_offsets = [ 0.0, -1.5, 0;...
                     0.0,  0.0, 0;...
                     0.0,  1.5, 0;...
                    -1.5, -1.5, 0;...
                    -1.5,  0.0, 0;...
                    -1.5,  1.5, 0;...
                    -3.0, -1.5, 0;...
                    -3.0,  0.0, 0;...
                    -3.0,  1.5, 0;...
                    -4.5, -1.5, 0;...
                    -4.5,  0.0, 0;...
                    -4.5,  1.5, 0;...
                  ];

figure();
hold on;
for idx = 1:length(model_names)
  topic_name = strcat('/', model_names(idx), '/odom')
  odom_msgs(idx) = select(bag, 'Topic', char(topic_name));
  odom(idx) = timeseries(odom_msgs(idx), 'Pose.Pose.Position.X', 'Pose.Pose.Position.Y', 'Pose.Pose.Position.Z');
end
axis equal

%% Plotting
for idx = 1:length(model_names)
  plot_handles(idx) = scatter3(odom(idx).Data(1,1), odom(idx).Data(1,2), odom(idx).Data(1,3));
end

for tt = 1:size(odom(1).Data, 1)
    for idx = 1:length(model_names)
        plot_handles(idx).set('xdata', odom(idx).Data(tt,1), ...
            'ydata', odom(idx).Data(tt,2), ...
            'zdata', odom(idx).Data(tt,3));
    end
    drawnow();
    pause(.01);
end


% %%
% drift = norm(odom.Data(1,:) - odom.Data(end,:));
% dx = diff(odom.Data(:,:));
% dist_dx = arrayfun(@(idx) norm(dx(idx,:)), 1:size(dx,1));
% dist_travelled = sum(dist_dx);
% drift_percent = (drift / dist_travelled)*100
